name: release-please

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: rp
        uses: googleapis/release-please-action@v4
        with:
          # Single-package Go repo:
          release-type: go
          package-name: cpout
          bump-minor-pre-major: true
          token: ${{ secrets.GITHUB_TOKEN }}
